# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="GENEHACK"


inherit perl-module

DESCRIPTION="Wrap git(7) command-line interface"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Most
	dev-perl/Sort-Versions
	dev-perl/Test-Deep
	dev-perl/Test-Exception
	dev-perl/File-pushd
	perl-gcpan/Env-Path
	dev-lang/perl"
