# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="GFUJI"


inherit perl-module

DESCRIPTION="Organize your Mouse types in libraries"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Exception
	>=dev-perl/Any-Moose-0.200.0
	>=dev-perl/Mouse-1.40.0
	dev-lang/perl"
