# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="RJBS"


inherit perl-module

DESCRIPTION="a thing with a message method"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/namespace-clean
	dev-perl/Try-Tiny
	dev-perl/Moose
	perl-gcpan/String-Errf
	dev-perl/MooseX-Role-Parameterized
	dev-lang/perl"
